In [1]:
import numpy as np # forlinear algebra
import matplotlib.pyplot as plt #for plotting things
import os
import pandas as pd

# Keras Libraries
import keras
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.preprocessing.image import ImageDataGenerator, load_img
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

In [2]:
#load the train dataset
train_data=pd.read_csv('Train.csv')
train_data

,Unnamed: 0,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C159,C160,C161,C162,C163,C164,C165,C166,C167,STATUS
0,T1,0,6.96,0,99.781,0,8.12,116.087,598.864,0,...,2195,39.844,4.676,130.961,44.875,0,28.008,0.175,5.399,PASS
1,T2,0,7.565,0,99.921,0,8.268,116.76,605.493,0,...,2195,40.41,4.71,131.901,40.438,0,28.006,0.171,5.401,PASS
2,T3,0,11.771,0,99.833,0,8.269,121.81,604.341,0,...,2195,39.442,4.951,138.66,43,0,28.008,0.17,5.399,PASS
3,T4,0,0.62,0,100.481,0,8.281,109.595,597.332,0,...,2195,40.128,4.611,129.158,42.75,0,28.008,0.17,5.399,PASS
4,T5,0,1.043,0,100.018,0,8.214,109.5,600.467,0,...,2195,39.625,4.763,133.42,43.5,0,28.008,0.17,5.400,PASS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,T1996,,0.775,,99.447,,8.232,108.74,598.499,,...,2195,39.799,4.808,134.673,42.875,,28.009,0.166,5.399,FAIL
1996,T1997,0,2.826,1200,99.726,1525,8.247,111.199,600.396,708,...,2195,39.38,4.909,137.492,43.5,0,28.007,0.168,5.400,FAIL
1997,T1998,,2.42,,99.454,,8.251,110.606,600.544,,...,2195,40.369,4.981,139.499,44.25,,28.007,0.165,5.401,FAIL
1998,T1999,,0.437,,100.163,,8.22,109.067,604.628,,...,2195,39.112,4.844,135.666,43.188,,28.006,0.166,5.401,FAIL
1999,T2000,,1.703,,100.377,,8.314,110.738,598.356,,...,2195,39.396,4.649,130.208,40.75,,28.009,0.169,5.399,FAIL

In [3]:
train_data1 = train_data.replace(' ', np.nan)  # to get rid of empty values
train_data2 = train_data1.replace(' NA', np.nan)# standardise the nan values       
train=train_data2.dropna()#remove the nan values from train dataset
train_df=train.drop('Unnamed: 0', axis=1)
train_df

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,...,C159,C160,C161,C162,C163,C164,C165,C166,C167,STATUS
0,0,6.96,0,99.781,0,8.12,116.087,598.864,0,603.605,...,2195,39.844,4.676,130.961,44.875,0,28.008,0.175,5.399,PASS
1,0,7.565,0,99.921,0,8.268,116.76,605.493,0,600.802,...,2195,40.41,4.71,131.901,40.438,0,28.006,0.171,5.401,PASS
2,0,11.771,0,99.833,0,8.269,121.81,604.341,0,597.587,...,2195,39.442,4.951,138.66,43,0,28.008,0.17,5.399,PASS
3,0,0.62,0,100.481,0,8.281,109.595,597.332,0,602.017,...,2195,40.128,4.611,129.158,42.75,0,28.008,0.17,5.399,PASS
4,0,1.043,0,100.018,0,8.214,109.5,600.467,0,602.048,...,2195,39.625,4.763,133.42,43.5,0,28.008,0.17,5.400,PASS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1984,0,0.868,1200,100.326,1617,8.329,109.731,599.181,702,603.255,...,2195,39.854,4.73,132.467,43.125,0,28.005,0.16,5.400,FAIL
1986,0,0.709,1200,100.406,1630,8.246,109.693,597.979,732,602.049,...,2195,39.098,4.549,127.441,40.75,0,28.011,0.16,5.402,FAIL
1990,0,2.191,1200,100.184,1548,7.569,110.623,604.183,727,599.594,...,2195,39.189,4.812,134.78,43.188,0,28.008,0.177,5.400,FAIL
1993,0,2.191,1200,100.184,1548,7.569,110.623,604.183,727,599.594,...,2195,39.189,4.812,134.78,43.188,0,28.008,0.177,5.400,FAIL
1996,0,2.826,1200,99.726,1525,8.247,111.199,600.396,708,598.676,...,2195,39.38,4.909,137.492,43.5,0,28.007,0.168,5.400,FAIL

In [4]:
df_transformed=pd.get_dummies(train_df, prefix=['STATUS'], columns=['STATUS'])#convert the string variables into numeric variables
df_transform=df_transformed.drop(['STATUS_FAIL'], axis=1)# only 1 column is needed
df_transform

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,...,C159,C160,C161,C162,C163,C164,C165,C166,C167,STATUS_PASS
0,0,6.96,0,99.781,0,8.12,116.087,598.864,0,603.605,...,2195,39.844,4.676,130.961,44.875,0,28.008,0.175,5.399,1
1,0,7.565,0,99.921,0,8.268,116.76,605.493,0,600.802,...,2195,40.41,4.71,131.901,40.438,0,28.006,0.171,5.401,1
2,0,11.771,0,99.833,0,8.269,121.81,604.341,0,597.587,...,2195,39.442,4.951,138.66,43,0,28.008,0.17,5.399,1
3,0,0.62,0,100.481,0,8.281,109.595,597.332,0,602.017,...,2195,40.128,4.611,129.158,42.75,0,28.008,0.17,5.399,1
4,0,1.043,0,100.018,0,8.214,109.5,600.467,0,602.048,...,2195,39.625,4.763,133.42,43.5,0,28.008,0.17,5.400,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1984,0,0.868,1200,100.326,1617,8.329,109.731,599.181,702,603.255,...,2195,39.854,4.73,132.467,43.125,0,28.005,0.16,5.400,0
1986,0,0.709,1200,100.406,1630,8.246,109.693,597.979,732,602.049,...,2195,39.098,4.549,127.441,40.75,0,28.011,0.16,5.402,0
1990,0,2.191,1200,100.184,1548,7.569,110.623,604.183,727,599.594,...,2195,39.189,4.812,134.78,43.188,0,28.008,0.177,5.400,0
1993,0,2.191,1200,100.184,1548,7.569,110.623,604.183,727,599.594,...,2195,39.189,4.812,134.78,43.188,0,28.008,0.177,5.400,0
1996,0,2.826,1200,99.726,1525,8.247,111.199,600.396,708,598.676,...,2195,39.38,4.909,137.492,43.5,0,28.007,0.168,5.400,0

In [5]:
#standarise the dataset, except the label column('STATUS_PASS')
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_transform.iloc[:, :-1]=scaler.fit_transform(df_transform.iloc[:, :-1])
df_transform

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,...,C159,C160,C161,C162,C163,C164,C165,C166,C167,STATUS_PASS
0,0.0,0.463569,0.0,0.448732,0.000000,0.641466,0.458139,0.479383,0.000000,0.913734,...,0.0,0.476033,0.331204,0.330715,0.640267,0.0,0.500000,0.867925,0.00,1
1,0.0,0.503900,0.0,0.525910,0.000000,0.810997,0.494188,0.879009,0.000000,0.630259,...,0.0,0.619579,0.362226,0.361352,0.129504,0.0,0.166667,0.792453,0.50,1
2,0.0,0.784281,0.0,0.477398,0.000000,0.812142,0.764690,0.809561,0.000000,0.305117,...,0.0,0.374081,0.582117,0.581644,0.424427,0.0,0.500000,0.773585,0.00,1
3,0.0,0.040931,0.0,0.834620,0.000000,0.825888,0.110397,0.387027,0.000000,0.753135,...,0.0,0.548060,0.271898,0.271951,0.395649,0.0,0.500000,0.773585,0.00,1
4,0.0,0.069129,0.0,0.579383,0.000000,0.749141,0.105308,0.576019,0.000000,0.756270,...,0.0,0.420492,0.410584,0.410860,0.481985,0.0,0.500000,0.773585,0.25,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1984,0.0,0.057463,1.0,0.749173,0.947276,0.880871,0.117682,0.498493,0.893130,0.878337,...,0.0,0.478570,0.380474,0.379799,0.438817,0.0,0.000000,0.584906,0.25,0
1986,0.0,0.046864,1.0,0.793275,0.954892,0.785796,0.115646,0.426031,0.931298,0.756371,...,0.0,0.286837,0.215328,0.215990,0.165420,0.0,1.000000,0.584906,0.75,0
1990,0.0,0.145657,1.0,0.670893,0.906854,0.010309,0.165461,0.800036,0.924936,0.508091,...,0.0,0.309916,0.455292,0.455185,0.446069,0.0,0.500000,0.905660,0.25,0
1993,0.0,0.145657,1.0,0.670893,0.906854,0.010309,0.165461,0.800036,0.924936,0.508091,...,0.0,0.309916,0.455292,0.455185,0.446069,0.0,0.500000,0.905660,0.25,0
1996,0.0,0.187987,1.0,0.418412,0.893380,0.786942,0.196315,0.571739,0.900763,0.415251,...,0.0,0.358357,0.543796,0.543576,0.481985,0.0,0.333333,0.735849,0.25,0

In [6]:
#Spilt the dataset into train, test
from sklearn.model_selection import train_test_split
y = df_transform['STATUS_PASS']
X = df_transform.drop('STATUS_PASS',axis=1)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)

**Run the ANN model**

In [7]:
model = Sequential()
model.add(Dense(12, input_dim=167, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [8]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [9]:
model.fit(X_train, y_train, epochs=150, batch_size=10)

Epoch 1/150
136/136 [==============================] - 1s 700us/step - loss: 0.1370 - accuracy: 0.9808
Epoch 2/150
136/136 [==============================] - 0s 819us/step - loss: 0.0897 - accuracy: 0.9808
Epoch 3/150
136/136 [==============================] - 0s 741us/step - loss: 0.0792 - accuracy: 0.9808
Epoch 4/150
136/136 [==============================] - 0s 742us/step - loss: 0.0695 - accuracy: 0.9808
Epoch 5/150
136/136 [==============================] - 0s 819us/step - loss: 0.0630 - accuracy: 0.9808
Epoch 6/150
136/136 [==============================] - 0s 820us/step - loss: 0.0545 - accuracy: 0.9808
Epoch 7/150
136/136 [==============================] - 0s 719us/step - loss: 0.0490 - accuracy: 0.9830
Epoch 8/150
136/136 [==============================] - 0s 687us/step - loss: 0.0433 - accuracy: 0.9867
Epoch 9/150
136/136 [==============================] - 0s 742us/step - loss: 0.0384 - accuracy: 0.9897
Epoch 10/150
136/136 [==============================] - 0s 745us/step - loss: 0.0323 - accuracy: 0.9904
Epoch 11/150
136/136 [==============================] - 0s 741us/step - loss: 0.0327 - accuracy: 0.9919
Epoch 12/150
136/136 [==============================] - 0s 738us/step - loss: 0.0307 - accuracy: 0.9912
Epoch 13/150
136/136 [==============================] - 0s 744us/step - loss: 0.0274 - accuracy: 0.9912
Epoch 14/150
136/136 [==============================] - 0s 809us/step - loss: 0.0253 - accuracy: 0.9934
Epoch 15/150
136/136 [==============================] - 0s 834us/step - loss: 0.0238 - accuracy: 0.9934
Epoch 16/150
136/136 [==============================] - 0s 785us/step - loss: 0.0218 - accuracy: 0.9926
Epoch 17/150
136/136 [==============================] - 0s 785us/step - loss: 0.0212 - accuracy: 0.9934
Epoch 18/150
136/136 [==============================] - 0s 675us/step - loss: 0.0190 - accuracy: 0.9926
Epoch 19/150
136/136 [==============================] - 0s 850us/step - loss: 0.0229 - accuracy: 0.9934
Epoch 20/150
136/136 [==============================] - 0s 778us/step - loss: 0.0168 - accuracy: 0.9956
Epoch 21/150
136/136 [==============================] - 0s 785us/step - loss: 0.0175 - accuracy: 0.9971
Epoch 22/150
136/136 [==============================] - 0s 815us/step - loss: 0.0162 - accuracy: 0.9963
Epoch 23/150
136/136 [==============================] - 0s 780us/step - loss: 0.0172 - accuracy: 0.9963
Epoch 24/150
136/136 [==============================] - 0s 771us/step - loss: 0.0162 - accuracy: 0.9963
Epoch 25/150
136/136 [==============================] - 0s 785us/step - loss: 0.0167 - accuracy: 0.9941
Epoch 26/150
136/136 [==============================] - 0s 795us/step - loss: 0.0142 - accuracy: 0.9963
Epoch 27/150
136/136 [==============================] - 0s 789us/step - loss: 0.0147 - accuracy: 0.9956
Epoch 28/150
136/136 [==============================] - 0s 720us/step - loss: 0.0156 - accuracy: 0.9956
Epoch 29/150
136/136 [==============================] - 0s 755us/step - loss: 0.0142 - accuracy: 0.9963
Epoch 30/150
136/136 [==============================] - 0s 740us/step - loss: 0.0117 - accuracy: 0.9971
Epoch 31/150
136/136 [==============================] - 0s 740us/step - loss: 0.0124 - accuracy: 0.9971
Epoch 32/150
136/136 [==============================] - 0s 741us/step - loss: 0.0129 - accuracy: 0.9963
Epoch 33/150
136/136 [==============================] - 0s 741us/step - loss: 0.0191 - accuracy: 0.9956
Epoch 34/150
136/136 [==============================] - 0s 799us/step - loss: 0.0122 - accuracy: 0.9963
Epoch 35/150
136/136 [==============================] - 0s 858us/step - loss: 0.0118 - accuracy: 0.9978
Epoch 36/150
136/136 [==============================] - 0s 778us/step - loss: 0.0112 - accuracy: 0.9971
Epoch 37/150
136/136 [==============================] - 0s 852us/step - loss: 0.0118 - accuracy: 0.9956
Epoch 38/150
136/136 [==============================] - 0s 793us/step - loss: 0.0092 - accuracy: 0.9971
Epoch 39/150
136/136 [==============================] - 0s 778us/step - loss: 0.0112 - accuracy: 0.9971
Epoch 40/150
136/136 [==============================] - 0s 793us/step - loss: 0.0113 - accuracy: 0.9978
Epoch 41/150
136/136 [==============================] - 0s 778us/step - loss: 0.0141 - accuracy: 0.9948
Epoch 42/150
136/136 [==============================] - 0s 645us/step - loss: 0.0106 - accuracy: 0.9971
Epoch 43/150
136/136 [==============================] - 0s 886us/step - loss: 0.0099 - accuracy: 0.9978
Epoch 44/150
136/136 [==============================] - 0s 784us/step - loss: 0.0099 - accuracy: 0.9971
Epoch 45/150
136/136 [==============================] - 0s 793us/step - loss: 0.0103 - accuracy: 0.9978
Epoch 46/150
136/136 [==============================] - 0s 767us/step - loss: 0.0085 - accuracy: 0.9978
Epoch 47/150
136/136 [==============================] - 0s 778us/step - loss: 0.0105 - accuracy: 0.9971
Epoch 48/150
136/136 [==============================] - 0s 770us/step - loss: 0.0081 - accuracy: 0.9978
Epoch 49/150
136/136 [==============================] - 0s 896us/step - loss: 0.0079 - accuracy: 0.9978
Epoch 50/150
136/136 [==============================] - 0s 814us/step - loss: 0.0081 - accuracy: 0.9993
Epoch 51/150
136/136 [==============================] - 0s 773us/step - loss: 0.0081 - accuracy: 0.9985
Epoch 52/150
136/136 [==============================] - 0s 771us/step - loss: 0.0079 - accuracy: 0.9971
Epoch 53/150
136/136 [==============================] - 0s 787us/step - loss: 0.0100 - accuracy: 0.9978
Epoch 54/150
136/136 [==============================] - 0s 714us/step - loss: 0.0103 - accuracy: 0.9971
Epoch 55/150
136/136 [==============================] - 0s 740us/step - loss: 0.0114 - accuracy: 0.9963
Epoch 56/150
136/136 [==============================] - 0s 743us/step - loss: 0.0083 - accuracy: 0.9978
Epoch 57/150
136/136 [==============================] - 0s 741us/step - loss: 0.0118 - accuracy: 0.9963
Epoch 58/150
136/136 [==============================] - 0s 740us/step - loss: 0.0083 - accuracy: 0.9978
Epoch 59/150
136/136 [==============================] - 0s 743us/step - loss: 0.0076 - accuracy: 0.9978
Epoch 60/150
136/136 [==============================] - 0s 741us/step - loss: 0.0069 - accuracy: 0.9978
Epoch 61/150
136/136 [==============================] - 0s 741us/step - loss: 0.0069 - accuracy: 0.9993
Epoch 62/150
136/136 [==============================] - 0s 896us/step - loss: 0.0167 - accuracy: 0.9948
Epoch 63/150
136/136 [==============================] - 0s 802us/step - loss: 0.0061 - accuracy: 0.9985
Epoch 64/150
136/136 [==============================] - 0s 778us/step - loss: 0.0065 - accuracy: 0.9985
Epoch 65/150
136/136 [==============================] - 0s 688us/step - loss: 0.0068 - accuracy: 0.9978
Epoch 66/150
136/136 [==============================] - 0s 872us/step - loss: 0.0068 - accuracy: 0.9978
Epoch 67/150
136/136 [==============================] - 0s 763us/step - loss: 0.0055 - accuracy: 0.9978
Epoch 68/150
136/136 [==============================] - 0s 673us/step - loss: 0.0066 - accuracy: 0.9985
Epoch 69/150
136/136 [==============================] - 0s 816us/step - loss: 0.0048 - accuracy: 0.9993
Epoch 70/150
136/136 [==============================] - 0s 703us/step - loss: 0.0054 - accuracy: 0.9993
Epoch 71/150
136/136 [==============================] - 0s 741us/step - loss: 0.0066 - accuracy: 0.9971
Epoch 72/150
136/136 [==============================] - 0s 836us/step - loss: 0.0057 - accuracy: 0.9993
Epoch 73/150
136/136 [==============================] - 0s 800us/step - loss: 0.0050 - accuracy: 0.9993
Epoch 74/150
136/136 [==============================] - 0s 668us/step - loss: 0.0059 - accuracy: 0.9978
Epoch 75/150
136/136 [==============================] - 0s 742us/step - loss: 0.0096 - accuracy: 0.9948
Epoch 76/150
136/136 [==============================] - 0s 740us/step - loss: 0.0056 - accuracy: 0.9993
Epoch 77/150
136/136 [==============================] - 0s 806us/step - loss: 0.0081 - accuracy: 0.9978
Epoch 78/150
136/136 [==============================] - 0s 800us/step - loss: 0.0050 - accuracy: 0.9978
Epoch 79/150

136/136 [==============================] - 0s 765us/step - loss: 0.0042 - accuracy: 0.9985
Epoch 80/150
136/136 [==============================] - 0s 793us/step - loss: 0.0058 - accuracy: 0.9985
Epoch 81/150
136/136 [==============================] - 0s 775us/step - loss: 0.0051 - accuracy: 0.9978
Epoch 82/150
136/136 [==============================] - 0s 785us/step - loss: 0.0030 - accuracy: 0.9993
Epoch 83/150
136/136 [==============================] - 0s 708us/step - loss: 0.0059 - accuracy: 0.9978
Epoch 84/150
136/136 [==============================] - 0s 796us/step - loss: 0.0043 - accuracy: 0.9993
Epoch 85/150
136/136 [==============================] - 0s 756us/step - loss: 0.0140 - accuracy: 0.9948
Epoch 86/150
136/136 [==============================] - 0s 661us/step - loss: 0.0049 - accuracy: 0.9985
Epoch 87/150
136/136 [==============================] - 0s 822us/step - loss: 0.0081 - accuracy: 0.9963
Epoch 88/150
136/136 [==============================] - 0s 779us/step - loss: 0.0057 - accuracy: 0.9978
Epoch 89/150
136/136 [==============================] - 0s 822us/step - loss: 0.0058 - accuracy: 0.9963
Epoch 90/150
136/136 [==============================] - 0s 745us/step - loss: 0.0062 - accuracy: 0.9978
Epoch 91/150
136/136 [==============================] - 0s 741us/step - loss: 0.0030 - accuracy: 0.9993
Epoch 92/150
136/136 [==============================] - 0s 805us/step - loss: 0.0030 - accuracy: 0.9985
Epoch 93/150
136/136 [==============================] - 0s 785us/step - loss: 0.0066 - accuracy: 0.9956
Epoch 94/150
136/136 [==============================] - 0s 666us/step - loss: 0.0022 - accuracy: 0.9993
Epoch 95/150
136/136 [==============================] - 0s 787us/step - loss: 0.0030 - accuracy: 0.9985
Epoch 96/150
136/136 [==============================] - 0s 741us/step - loss: 0.0019 - accuracy: 1.0000
Epoch 97/150
136/136 [==============================] - 0s 741us/step - loss: 0.0030 - accuracy: 0.9993
Epoch 98/150
136/136 [==============================] - 0s 852us/step - loss: 0.0024 - accuracy: 0.9993
Epoch 99/150
136/136 [==============================] - 0s 824us/step - loss: 0.0017 - accuracy: 1.0000
Epoch 100/150
136/136 [==============================] - 0s 719us/step - loss: 0.0025 - accuracy: 0.9993
Epoch 101/150
136/136 [==============================] - 0s 696us/step - loss: 0.0016 - accuracy: 1.0000
Epoch 102/150
136/136 [==============================] - 0s 838us/step - loss: 0.0020 - accuracy: 1.0000
Epoch 103/150
136/136 [==============================] - 0s 664us/step - loss: 0.0027 - accuracy: 0.9993
Epoch 104/150
136/136 [==============================] - 0s 849us/step - loss: 0.0019 - accuracy: 1.0000
Epoch 105/150
136/136 [==============================] - 0s 789us/step - loss: 0.0020 - accuracy: 0.9993
Epoch 106/150
136/136 [==============================] - 0s 682us/step - loss: 0.0022 - accuracy: 0.9993
Epoch 107/150
136/136 [==============================] - 0s 823us/step - loss: 0.0023 - accuracy: 0.9993
Epoch 108/150
136/136 [==============================] - 0s 793us/step - loss: 0.0026 - accuracy: 0.9985
Epoch 109/150
136/136 [==============================] - 0s 778us/step - loss: 0.0019 - accuracy: 0.9985
Epoch 110/150
136/136 [==============================] - 0s 740us/step - loss: 0.0014 - accuracy: 1.0000
Epoch 111/150
136/136 [==============================] - 0s 765us/step - loss: 0.0013 - accuracy: 1.0000
Epoch 112/150
136/136 [==============================] - 0s 800us/step - loss: 0.0012 - accuracy: 1.0000
Epoch 113/150
136/136 [==============================] - 0s 768us/step - loss: 8.8271e-04 - accuracy: 1.0000
Epoch 114/150
136/136 [==============================] - 0s 785us/step - loss: 0.0033 - accuracy: 0.9993
Epoch 115/150
136/136 [==============================] - 0s 734us/step - loss: 8.4821e-04 - accuracy: 1.0000
Epoch 116/150
136/136 [==============================] - 0s 771us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 117/150
136/136 [==============================] - 0s 713us/step - loss: 9.4310e-04 - accuracy: 1.0000
Epoch 118/150
136/136 [==============================] - 0s 877us/step - loss: 0.0021 - accuracy: 0.9993
Epoch 119/150
136/136 [==============================] - 0s 815us/step - loss: 0.0040 - accuracy: 0.9993
Epoch 120/150
136/136 [==============================] - 0s 778us/step - loss: 0.0040 - accuracy: 0.9985
Epoch 121/150
136/136 [==============================] - 0s 778us/step - loss: 6.4744e-04 - accuracy: 1.0000
Epoch 122/150
136/136 [==============================] - 0s 779us/step - loss: 0.0013 - accuracy: 1.0000
Epoch 123/150
136/136 [==============================] - 0s 687us/step - loss: 5.6250e-04 - accuracy: 1.0000
Epoch 124/150
136/136 [==============================] - 0s 741us/step - loss: 3.9633e-04 - accuracy: 1.0000
Epoch 125/150
136/136 [==============================] - 0s 738us/step - loss: 9.8589e-04 - accuracy: 1.0000
Epoch 126/150
136/136 [==============================] - 0s 778us/step - loss: 8.0299e-04 - accuracy: 1.0000
Epoch 127/150
136/136 [==============================] - 0s 696us/step - loss: 5.5540e-04 - accuracy: 1.0000
Epoch 128/150
136/136 [==============================] - 0s 886us/step - loss: 0.0020 - accuracy: 0.9985
Epoch 129/150
136/136 [==============================] - 0s 793us/step - loss: 4.6326e-04 - accuracy: 1.0000
Epoch 130/150
136/136 [==============================] - 0s 780us/step - loss: 5.4876e-04 - accuracy: 1.0000
Epoch 131/150
136/136 [==============================] - 0s 800us/step - loss: 4.0610e-04 - accuracy: 1.0000
Epoch 132/150
136/136 [==============================] - 0s 772us/step - loss: 2.7938e-04 - accuracy: 1.0000
Epoch 133/150
136/136 [==============================] - 0s 778us/step - loss: 3.6369e-04 - accuracy: 1.0000
Epoch 134/150
136/136 [==============================] - 0s 651us/step - loss: 3.0293e-04 - accuracy: 1.0000
Epoch 135/150
136/136 [==============================] - 0s 831us/step - loss: 2.6649e-04 - accuracy: 1.0000
Epoch 136/150
136/136 [==============================] - 0s 728us/step - loss: 5.8598e-04 - accuracy: 1.0000
Epoch 137/150
136/136 [==============================] - 0s 740us/step - loss: 2.2963e-04 - accuracy: 1.0000
Epoch 138/150
136/136 [==============================] - 0s 740us/step - loss: 4.3728e-04 - accuracy: 1.0000
Epoch 139/150
136/136 [==============================] - 0s 740us/step - loss: 3.3982e-04 - accuracy: 1.0000
Epoch 140/150
136/136 [==============================] - 0s 741us/step - loss: 2.9174e-04 - accuracy: 1.0000
Epoch 141/150
136/136 [==============================] - 0s 800us/step - loss: 3.3328e-04 - accuracy: 1.0000
Epoch 142/150
136/136 [==============================] - 0s 804us/step - loss: 1.7191e-04 - accuracy: 1.0000
Epoch 143/150
136/136 [==============================] - 0s 732us/step - loss: 4.6605e-04 - accuracy: 1.0000
Epoch 144/150
136/136 [==============================] - 0s 857us/step - loss: 0.0077 - accuracy: 0.9978
Epoch 145/150
136/136 [==============================] - 0s 797us/step - loss: 0.0249 - accuracy: 0.9948
Epoch 146/150
136/136 [==============================] - 0s 796us/step - loss: 5.2845e-04 - accuracy: 1.0000
Epoch 147/150
136/136 [==============================] - 0s 781us/step - loss: 3.2201e-04 - accuracy: 1.0000
Epoch 148/150
136/136 [==============================] - 0s 773us/step - loss: 2.8628e-04 - accuracy: 1.0000
Epoch 149/150
136/136 [==============================] - 0s 703us/step - loss: 3.2496e-04 - accuracy: 1.0000
Epoch 150/150
136/136 [==============================] - 0s 753us/step - loss: 2.7384e-04 - accuracy: 1.0000

In [10]:
#accuracy of ANN model
_, accuracy = model.evaluate(X_train, y_train)
print('Accuracy: %.2f' % (accuracy*100))

43/43 [==============================] - 0s 663us/step - loss: 2.7433e-04 - accuracy: 1.0000
Accuracy: 100.00

In [11]:
#generate out the predictions using ANN model
predictions = model.predict(X_test)
rounded = [round(x[0]) for x in predictions]

**Run ML model**

In [12]:
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

def model_selection(X_train, Y_train):
    models = []
    models.append(('RFC', RandomForestClassifier()))
    models.append(('ADA', AdaBoostClassifier()))
    models.append(('KNN', KNeighborsClassifier()))
    models.append(('RT', DecisionTreeClassifier()))
    models.append(('GBC', GradientBoostingClassifier()))
    models.append(('XGB', XGBClassifier()))
    models.append(('SVM', SVC()))
    models.append(('LR', LogisticRegression()))
    # evaluate each model in turn
    results = []
    names = []
    scoring = 'accuracy'
    for name, model in models:
        kfold = KFold(n_splits=5)
        cv_results = cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
        results.append(cv_results)
        names.append(name)
        msg = "%s: Accuracy: %f " % (name, abs(cv_results.mean()))
        print(msg)

In [13]:
model_selection(X_train, y_train)

RFC: Accuracy: 0.990409
ADA: Accuracy: 0.986721
KNN: Accuracy: 0.988933
RT: Accuracy: 0.982293
GBC: Accuracy: 0.985245
XGB: Accuracy: 0.990409
SVM: Accuracy: 0.990409
LR: Accuracy: 0.990409

In [14]:
test_data=pd.read_csv('Test.csv')
test_data

,Unnamed: 0,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C158,C159,C160,C161,C162,C163,C164,C165,C166,C167
0,T1,0,1.983,1200,100.459,1557,8.227,111.008,601.395,713,...,38.773,2195,39.436,5.161,144.55,42.438,0,28.008,0.158,5.398
1,T2,0,1.558,1200,100.402,1573,8.259,110.522,598.414,737,...,38.582,2195,38.658,5.199,145.624,45.875,0,28.007,0.168,5.400
2,T3,0,0.305,1200,100.399,1684,8.193,109.026,598.144,727,...,38.028,2195,40.333,5.267,147.514,42.313,0,28.009,0.169,5.400
3,T4,0,2.235,1200,100.280,1551,8.240,111.068,601.174,730,...,38.383,2195,38.457,5.227,146.373,43.188,0,28.004,0.169,5.400
4,T5,0,0.320,1200,100.588,1681,8.088,109.145,597.784,734,...,37.286,2195,39.556,5.366,150.304,43.063,0,28.012,0.158,5.403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,T496,0,0.236,1200,100.573,1686,8.285,109.241,598.326,735,...,36.764,2195,38.397,5.46,152.935,44.375,0,28.011,0.160,5.403
496,T497,,0.725,,100.420,,8.307,109.704,604.137,,...,NA,NA,NA,NA,NA,NA,,28.007,0.167,5.400
497,T498,0,0.862,1200,100.061,1627,8.249,109.304,597.530,732,...,43.409,2195,39.126,4.624,129.538,41,0,28.011,0.160,5.403
498,T499,,5.927,,99.967,,8.324,115.093,599.949,,...,42.36,2195,40.301,4.744,132.867,38.188,,28.007,0.166,5.401
499,T500,,2.066,,100.236,,8.310,111.070,606.335,,...,41.505,2195,39.742,4.841,135.581,41.938,,28.007,0.167,5.400

In [15]:
test_data1 = test_data.replace(' ', np.nan)  # to get rid of empty values
test_data2 = test_data1.replace(' NA', np.nan)       
test=test_data2.dropna()
test_df=test.drop('Unnamed: 0', axis=1)
test_df

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,...,C158,C159,C160,C161,C162,C163,C164,C165,C166,C167
0,0,1.983,1200,100.459,1557,8.227,111.008,601.395,713,603.299,...,38.773,2195,39.436,5.161,144.55,42.438,0,28.008,0.158,5.398
1,0,1.558,1200,100.402,1573,8.259,110.522,598.414,737,603.175,...,38.582,2195,38.658,5.199,145.624,45.875,0,28.007,0.168,5.400
2,0,0.305,1200,100.399,1684,8.193,109.026,598.144,727,603.483,...,38.028,2195,40.333,5.267,147.514,42.313,0,28.009,0.169,5.400
3,0,2.235,1200,100.280,1551,8.240,111.068,601.174,730,598.381,...,38.383,2195,38.457,5.227,146.373,43.188,0,28.004,0.169,5.400
4,0,0.320,1200,100.588,1681,8.088,109.145,597.784,734,601.415,...,37.286,2195,39.556,5.366,150.304,43.063,0,28.012,0.158,5.403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,0,2.104,1200,100.484,1550,7.551,110.695,600.610,728,596.084,...,40.972,2195,38.955,4.891,136.999,42.625,0,28.008,0.176,5.400
490,0,3.616,1200,100.186,1541,8.275,112.781,605.192,711,603.228,...,41.749,2195,38.851,4.807,134.65,42.125,0,28.009,0.168,5.400
492,0,1.457,1200,100.389,1575,8.248,110.509,606.334,754,600.392,...,42.861,2195,40.341,4.676,130.961,42.75,0,28.005,0.160,5.400
495,0,0.236,1200,100.573,1686,8.285,109.241,598.326,735,602.176,...,36.764,2195,38.397,5.46,152.935,44.375,0,28.011,0.160,5.403
497,0,0.862,1200,100.061,1627,8.249,109.304,597.530,732,602.624,...,43.409,2195,39.126,4.624,129.538,41,0,28.011,0.160,5.403

In [16]:
df_test=scaler.fit_transform(test_df)

In [17]:
predictions_test = model.predict(df_test)
rounded_test = [round(x[0]) for x in predictions_test]

In [18]:
test_df["prediction_ANN"]=rounded_test

In [19]:
rfc = RandomForestClassifier()

In [20]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [21]:
predictions_ML = rfc.predict(df_test)
test_df["prediction_ML"]=predictions_ML

C:\Users\TEE\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [22]:
#showcase of ANN's predictions and ML's predictions
test_df

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,...,C160,C161,C162,C163,C164,C165,C166,C167,prediction_ANN,prediction_ML
0,0,1.983,1200,100.459,1557,8.227,111.008,601.395,713,603.299,...,39.436,5.161,144.55,42.438,0,28.008,0.158,5.398,1,1
1,0,1.558,1200,100.402,1573,8.259,110.522,598.414,737,603.175,...,38.658,5.199,145.624,45.875,0,28.007,0.168,5.400,1,1
2,0,0.305,1200,100.399,1684,8.193,109.026,598.144,727,603.483,...,40.333,5.267,147.514,42.313,0,28.009,0.169,5.400,1,1
3,0,2.235,1200,100.280,1551,8.240,111.068,601.174,730,598.381,...,38.457,5.227,146.373,43.188,0,28.004,0.169,5.400,1,1
4,0,0.320,1200,100.588,1681,8.088,109.145,597.784,734,601.415,...,39.556,5.366,150.304,43.063,0,28.012,0.158,5.403,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,0,2.104,1200,100.484,1550,7.551,110.695,600.610,728,596.084,...,38.955,4.891,136.999,42.625,0,28.008,0.176,5.400,1,0
490,0,3.616,1200,100.186,1541,8.275,112.781,605.192,711,603.228,...,38.851,4.807,134.65,42.125,0,28.009,0.168,5.400,0,0
492,0,1.457,1200,100.389,1575,8.248,110.509,606.334,754,600.392,...,40.341,4.676,130.961,42.75,0,28.005,0.160,5.400,0,0
495,0,0.236,1200,100.573,1686,8.285,109.241,598.326,735,602.176,...,38.397,5.46,152.935,44.375,0,28.011,0.160,5.403,1,1
497,0,0.862,1200,100.061,1627,8.249,109.304,597.530,732,602.624,...,39.126,4.624,129.538,41,0,28.011,0.160,5.403,1,0

In [23]:
#classification report for ANN's model
print(classification_report(y_test,rounded))

              precision    recall  f1-score   support

           0       0.78      0.58      0.67        12
           1       0.99      1.00      0.99       570

    accuracy                           0.99       582
   macro avg       0.88      0.79      0.83       582
weighted avg       0.99      0.99      0.99       582

In [24]:
predictions_ml = rfc.predict(X_test)

In [25]:
#classification report for ML's model
print(classification_report(y_test,predictions_ml))

              precision    recall  f1-score   support

           0       0.75      0.25      0.38        12
           1       0.98      1.00      0.99       570

    accuracy                           0.98       582
   macro avg       0.87      0.62      0.68       582
weighted avg       0.98      0.98      0.98       582

**Conclusion**

It seems that both ANN and random forest models run well for this dataset and generated out the predictions at very high accuracy. As this dataset is unknown, thus very diffcult to conclude that which model is the best choice for this data.